version: "3"
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres
    volumes:
      - .:/app
      - .database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ultraSafePass
    ports:
      - 5464:5432
    restart: unless-stopped
  jdk:
    image: maven:3.5-jdk-8
    working_dir: /app
    container_name: jdk
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8808:8080
    command: mvn clean spring-boot:run
    restart: unless-stopped
    depends_on:
      - db