spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db/callcenter}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:ultraSafePass}

  jackson:
    property-naming-strategy: SNAKE_CASE